
spring:
  application:
    name: todo-app-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/tododb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # or your preferred setting for database schema management
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

other:
  secret-key: d505d8453a1621ece0ff7148809d14d94412a58127e4698002ed75676028fd3c244836e573a67c3065b127b64330a42712007815a8a6f6afa16fb40fa5c1efd4
